### ISSUE TITLE
Expose the entire router state in data function

### ISSUE THREAD

**Issue by amoutonbrady** [ryansolid/solid-app-router#7]
I guess it would be more of a discussion than an issue, but while working on the real world example rewritten with solid app router, I encountered a situation where I'd like to access the router.location and listen to the change within the data function.

I thought about just using the `useRouter` and access `router.location` but it turns out we can't access this context in data functions. Digging a bit into the source code, I figured you manually generate getters for query and params to be passed into the data function props.

Is there a reason we just don't feed the whole state proxy into the data function here:

https://github.com/ryansolid/solid-app-router/blob/bb251041c245ed2247cbb1885f16acf981c11e70/src/index.tsx#L205-L212

Like so:
```ts
return levels[i].handler.data!(state); 
```

I did patch it locally and it seems to work and since the proxy already exist I don't think we pay any perf price. That being said, I guess we are exposing more than the user could ever need.. And I would understand if you'd prefer discarding that issue.

**Comment by ryansolid** [comment]
I think this is reasonable. Especially now that I've hoisted it and router levels are no more than index used to resolve nested Routes. I had different behavior since I constructed params differently. And now that I've hoisted it above as you say you can't access that context. Which is an interesting point on it's own as it means the router needs to be the lowest global context, if you want to be able to read from context above it. It also mean data functions are outside of the tree so they can't leverage any nested contexts. I realized this while implementing and I'm not sure there is much to do for it since to parallelize nested we need to do this. With this setup we can navigate to..
`users/123/settings` and load both the `user page` and the `user settings sub page` in parallel while loading the data for both in parallel as well.

It does leave some questions on cascading data loads. Like what if the settings doesn't have enough from the url to know what data it needs, and needs to wait for the parents data to load first. In that case though I guess you wouldn't bother with a nested data component since you can't fetch in parallel anyway. Basically the view hierarchy can communicate to each other through props on the Route component or Context, but the data hierarchy has no similar way to communicate now that i've hoisted it. And in fact outside of a global store or props cannot communicate its results (nested contexts aren't available). These restrictions seem mostly fine but I feel like we can do better.

The answer might be related to this suggestion. Anything stored on the router itself would form a singleton context of sorts. But cleanup might be obvious. Anyway this is the sort of thing I'm thinking about.

**Comment by ryansolid** [comment]
Ok done in 0.0.33. Also add `NavLink` and `isActive`

**Comment by amoutonbrady** [comment]
Aweesome! Thank you Ryan, that'll be really helpful!
